name: Psychics
main: io.github.monun.psychics.plugin.PsychicsPlugin
api-version: '1.21'
version: $version
author: Monun
libraries:
  - io.github.anblusis:tap-core:1.0.3
  - xyz.icetang.lib:invfx-core:3.3.3
  - io.github.anblusis:kommand-core:1.0.1

